# Generated by Django 6.0.2 on 2026-02-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Total number of this asset in inventory'),
        ),
    ]
